name: radiochimbita
description: "Aplicacion para la radio mas chimbita."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/station.png
    - assets/images/volver.png
    - assets/images/facebook.png
    - assets/images/google.png
  uses-material-design: true
